-- Gerado por Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   em:        2025-03-21 22:10:25 BRT
--   site:      Oracle Database 11g
--   tipo:      Oracle Database 11g

/*
GRUPO:
Luis Miguel - 565324
Adeilson Laureano - 566282
Carlos Eduardo de Sousa - 565094
Luan Antônio Gomes Pereira - 552638
*/


DROP TABLE T_SGV_BAIRRO CASCADE CONSTRAINTS 
;

DROP TABLE T_SGV_CATEGORIA_PROD CASCADE CONSTRAINTS 
;

DROP TABLE T_SGV_CIDADE CASCADE CONSTRAINTS 
;

DROP TABLE T_SGV_CLASSIFICACAO_VIDEO CASCADE CONSTRAINTS 
;

DROP TABLE T_SGV_CLI_FISICA CASCADE CONSTRAINTS 
;

DROP TABLE T_SGV_CLI_JURIDICA CASCADE CONSTRAINTS 
;

DROP TABLE T_SGV_CLI_TEL CASCADE CONSTRAINTS 
;

DROP TABLE T_SGV_CLIENTE CASCADE CONSTRAINTS 
;

DROP TABLE T_SGV_DEPTO CASCADE CONSTRAINTS 
;

DROP TABLE T_SGV_END_CLI CASCADE CONSTRAINTS 
;

DROP TABLE T_SGV_END_FUNC CASCADE CONSTRAINTS 
;

DROP TABLE T_SGV_ESTADO CASCADE CONSTRAINTS 
;

DROP TABLE T_SGV_FUNC_TEL CASCADE CONSTRAINTS 
;

DROP TABLE T_SGV_FUNCIONARIO CASCADE CONSTRAINTS 
;

DROP TABLE T_SGV_LOGRADOURO CASCADE CONSTRAINTS 
;

DROP TABLE T_SGV_PRODUTO CASCADE CONSTRAINTS 
;

DROP TABLE T_SGV_SAC CASCADE CONSTRAINTS 
;

DROP TABLE T_SGV_TELEFONE CASCADE CONSTRAINTS 
;

DROP TABLE T_SGV_TIPO_TELEFONE CASCADE CONSTRAINTS 
;

DROP TABLE T_SGV_VIDEO CASCADE CONSTRAINTS 
;

DROP TABLE T_SGV_VISUALIZACAO_VIDEO CASCADE CONSTRAINTS 
;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE T_SGV_BAIRRO 
    ( 
     cd_bairro      NUMBER (8)  GENERATED BY DEFAULT AS IDENTITY , 
     cd_cidade      NUMBER (8)  NOT NULL , 
     nm_bairro      VARCHAR2 (45)  NOT NULL , 
     nm_zona_bairro VARCHAR2 (20) 
    ) 
;

COMMENT ON TABLE T_SGV_BAIRRO IS 'Armazena os dados dos bairros, incluindo o nome do bairro, a cidade à qual pertence e a zona (ex: Norte, Sul, Leste, Oeste).'
;

COMMENT ON COLUMN T_SGV_BAIRRO.cd_bairro IS 'Chave primária que identifica unicamente cada bairro.' 
;

COMMENT ON COLUMN T_SGV_BAIRRO.cd_cidade IS 'Chave estrangeira que identifica a cidade ao qual o bairro pertence.' 
;

COMMENT ON COLUMN T_SGV_BAIRRO.nm_bairro IS 'Nome do bairro.' 
;

COMMENT ON COLUMN T_SGV_BAIRRO.nm_zona_bairro IS 'Zona do bairro (ex: Norte, Sul, Leste, Oeste).' 
;

ALTER TABLE T_SGV_BAIRRO 
    ADD CONSTRAINT PK_SGV_BAIRRO PRIMARY KEY ( cd_bairro ) ;

CREATE TABLE T_SGV_CATEGORIA_PROD 
    ( 
     cd_categoria NUMBER (7)  GENERATED ALWAYS AS IDENTITY , 
     ds_categoria VARCHAR2 (500)  NOT NULL , 
     dt_inicio    DATE  NOT NULL , 
     dt_termino   DATE , 
     st_categoria CHAR (1)  NOT NULL 
    ) 
;

COMMENT ON TABLE T_SGV_CATEGORIA_PROD IS 'Armazena as categorias de produtos, incluindo descrição, tipo, datas de início e término, e status.'
;

COMMENT ON COLUMN T_SGV_CATEGORIA_PROD.cd_categoria IS 'Chave primária que identifica unicamente cada categoria de produto.' 
;

COMMENT ON COLUMN T_SGV_CATEGORIA_PROD.ds_categoria IS 'Descrição da categoria de produto.' 
;

COMMENT ON COLUMN T_SGV_CATEGORIA_PROD.dt_inicio IS 'Data de início da vigência da categoria.' 
;

COMMENT ON COLUMN T_SGV_CATEGORIA_PROD.dt_termino IS 'Data de término da vigência da categoria.' 
;

COMMENT ON COLUMN T_SGV_CATEGORIA_PROD.st_categoria IS 'Status da categoria (ex: A = Ativo, I = Inativo).' 
;

ALTER TABLE T_SGV_CATEGORIA_PROD 
    ADD CONSTRAINT CK_SGV_CATEGORIA_PROD_STATUS 
    CHECK (st_categoria IN ('A', 'I')
)
;


ALTER TABLE T_SGV_CATEGORIA_PROD 
    ADD CONSTRAINT CK_SGV_CATEGORIA_PROD_DATA 
    CHECK (dt_termino IS NULL OR dt_termino > dt_inicio)
;
ALTER TABLE T_SGV_CATEGORIA_PROD 
    ADD CONSTRAINT PK_SGV_CATEGORIA_PROD PRIMARY KEY ( cd_categoria ) ;

ALTER TABLE T_SGV_CATEGORIA_PROD 
    ADD CONSTRAINT UN_SGV_CATEG_PROD_DESCRICAO UNIQUE ( ds_categoria ) ;

CREATE TABLE T_SGV_CIDADE 
    ( 
     cd_cidade NUMBER (8)  GENERATED BY DEFAULT AS IDENTITY , 
     sg_estado CHAR (2)  NOT NULL , 
     nm_cidade VARCHAR2 (60)  NOT NULL , 
     cd_ibge   NUMBER (8)  NOT NULL , 
     nr_ddd    NUMBER (3) 
    ) 
;

COMMENT ON TABLE T_SGV_CIDADE IS 'Armazena os dados das cidades, incluindo o nome da cidade, o estado ao qual pertence, o código IBGE e o DDD.'
;

COMMENT ON COLUMN T_SGV_CIDADE.cd_cidade IS 'Chave primária que identifica unicamente cada cidade.' 
;

COMMENT ON COLUMN T_SGV_CIDADE.sg_estado IS 'Chave estrangeira que identifica o estado ao qual a cidade pertence.' 
;

COMMENT ON COLUMN T_SGV_CIDADE.nm_cidade IS 'Nome da cidade.' 
;

COMMENT ON COLUMN T_SGV_CIDADE.cd_ibge IS 'Código IBGE da cidade.' 
;

COMMENT ON COLUMN T_SGV_CIDADE.nr_ddd IS 'Código DDD da cidade.' 
;

ALTER TABLE T_SGV_CIDADE 
    ADD CONSTRAINT PK_SGV_CIDADE PRIMARY KEY ( cd_cidade ) ;

CREATE TABLE T_SGV_CLASSIFICACAO_VIDEO 
    ( 
     cd_classificacao NUMBER (7)  GENERATED ALWAYS AS IDENTITY , 
     ds_classificacao VARCHAR2 (80)  NOT NULL 
    ) 
;

COMMENT ON TABLE T_SGV_CLASSIFICACAO_VIDEO IS 'Armazena as classificações dos vídeos, como faixa etária ou conteúdo.'
;

COMMENT ON COLUMN T_SGV_CLASSIFICACAO_VIDEO.cd_classificacao IS 'Chave primária que identifica unicamente cada classificação de vídeo.' 
;

COMMENT ON COLUMN T_SGV_CLASSIFICACAO_VIDEO.ds_classificacao IS 'Descrição da classificação (ex: Livre, 12 anos, 18 anos).' 
;

ALTER TABLE T_SGV_CLASSIFICACAO_VIDEO 
    ADD CONSTRAINT PK_SGV_CLASSIFICACAO_VIDEO PRIMARY KEY ( cd_classificacao ) ;

CREATE TABLE T_SGV_CLI_FISICA 
    ( 
     nr_cliente        NUMBER (10)  NOT NULL , 
     num_cpf           CHAR (11)  NOT NULL , 
     dt_nascimento     DATE  NOT NULL , 
     sg_sexo_biologico CHAR (1)  NOT NULL , 
     ds_genero         VARCHAR2 (100) 
    ) 
;

COMMENT ON TABLE T_SGV_CLI_FISICA IS 'Armazena os dados específicos de clientes físicos, como CPF, data de nascimento e sexo biológico.'
;

COMMENT ON COLUMN T_SGV_CLI_FISICA.nr_cliente IS 'Chave primária e estrangeira que identifica o cliente (relacionada com T_SGV_CLIENTE).' 
;

COMMENT ON COLUMN T_SGV_CLI_FISICA.num_cpf IS 'CPF do cliente (11 dígitos numéricos).' 
;

COMMENT ON COLUMN T_SGV_CLI_FISICA.dt_nascimento IS 'Data de nascimento do cliente.' 
;

COMMENT ON COLUMN T_SGV_CLI_FISICA.sg_sexo_biologico IS 'Sexo biológico do cliente (ex: M = Masculino, F = Feminino, O = Outros).' 
;

COMMENT ON COLUMN T_SGV_CLI_FISICA.ds_genero IS 'Gênero com o qual o cliente se identifica.' 
;

ALTER TABLE T_SGV_CLI_FISICA 
    ADD CONSTRAINT CK_SGV_CLI_FISICA_SEXO 
    CHECK (sg_sexo_biologico IN ('M', 'F', 'O'))
;
ALTER TABLE T_SGV_CLI_FISICA 
    ADD CONSTRAINT PK_SGV_CLI_FISICA PRIMARY KEY ( nr_cliente ) ;

ALTER TABLE T_SGV_CLI_FISICA 
    ADD CONSTRAINT UN_SGV_CLI_FISICA_CPF UNIQUE ( num_cpf ) ;

CREATE TABLE T_SGV_CLI_JURIDICA 
    ( 
     nr_cliente   NUMBER (10)  NOT NULL , 
     dt_fundacao  DATE , 
     nr_cnpj      VARCHAR2 (20) , 
     nr_inscr_est VARCHAR2 (15) 
    ) 
;

COMMENT ON TABLE T_SGV_CLI_JURIDICA IS 'Armazena os dados específicos de clientes jurídicos, como CNPJ, data de fundação e inscrição estadual.'
;

COMMENT ON COLUMN T_SGV_CLI_JURIDICA.nr_cliente IS 'Chave primária e estrangeira que identifica o cliente (relacionada com T_SGV_CLIENTE).' 
;

COMMENT ON COLUMN T_SGV_CLI_JURIDICA.dt_fundacao IS 'Data de fundação da empresa.' 
;

COMMENT ON COLUMN T_SGV_CLI_JURIDICA.nr_cnpj IS 'CNPJ da empresa (14 dígitos numéricos).' 
;

COMMENT ON COLUMN T_SGV_CLI_JURIDICA.nr_inscr_est IS 'Inscrição estadual da empresa.' 
;

ALTER TABLE T_SGV_CLI_JURIDICA 
    ADD CONSTRAINT PK_SGV_CLI_JURIDICA PRIMARY KEY ( nr_cliente ) ;

CREATE TABLE T_SGV_CLI_TEL 
    ( 
     nr_cliente  NUMBER (10)  NOT NULL , 
     cd_telefone NUMBER (10)  NOT NULL 
    ) 
;

COMMENT ON TABLE T_SGV_CLI_TEL IS 'Armazena a relação entre clientes e seus telefones, permitindo que um cliente tenha múltiplos telefones cadastrados.'
;

COMMENT ON COLUMN T_SGV_CLI_TEL.nr_cliente IS 'Chave primária e estrangeira que identifica o cliente (relacionada com T_SGV_CLIENTE).' 
;

COMMENT ON COLUMN T_SGV_CLI_TEL.cd_telefone IS 'Chave primária e estrangeira que identifica o telefone (relacionada com T_SGV_TELEFONE).' 
;

ALTER TABLE T_SGV_CLI_TEL 
    ADD CONSTRAINT PK_SGV_CLI_TEL PRIMARY KEY ( nr_cliente, cd_telefone ) ;

CREATE TABLE T_SGV_CLIENTE 
    ( 
     nr_cliente      NUMBER (10)  GENERATED ALWAYS AS IDENTITY , 
     nm_cliente      VARCHAR2 (160)  NOT NULL , 
     qt_estrelas     NUMBER (1) , 
     vl_medio_compra NUMBER (10,2)  NOT NULL , 
     st_cliente      CHAR (1)  NOT NULL , 
     ds_email        VARCHAR2 (100) , 
     nm_login        VARCHAR2 (50)  NOT NULL , 
     ds_senha        VARCHAR2 (50)  NOT NULL , 
     tp_cliente      CHAR (2)  NOT NULL 
    ) 
;

COMMENT ON TABLE T_SGV_CLIENTE IS 'Armazena os dados dos clientes, incluindo informações pessoais, status e dados de login.'
;

COMMENT ON COLUMN T_SGV_CLIENTE.nr_cliente IS 'Chave primária que identifica unicamente cada cliente.' 
;

COMMENT ON COLUMN T_SGV_CLIENTE.nm_cliente IS 'Essa coluna irá armazenar o nome do cliente na plataforma ecommerce da Melhores Compras.' 
;

COMMENT ON COLUMN T_SGV_CLIENTE.qt_estrelas IS 'Essa coluna irá armazenar a quantiade de estrelas do cliente na plataforma ecommerce da Melhores Compras.' 
;

COMMENT ON COLUMN T_SGV_CLIENTE.vl_medio_compra IS 'Essa coluna irá armazenar o valor  médio de gastos feito pelo cliente na plataforma ecommerce da Melhores Compras.' 
;

COMMENT ON COLUMN T_SGV_CLIENTE.st_cliente IS 'Essa coluna irá armazenar o statuss do cliente da Melhores Compras. Os valores permitidos aqui são: A(tivo) e I(nativo).' 
;

COMMENT ON COLUMN T_SGV_CLIENTE.ds_email IS 'Essa coluna irá armazenar o email  do cliente da Melhores Compras.' 
;

COMMENT ON COLUMN T_SGV_CLIENTE.nm_login IS 'Essa coluna irá armazenar o login de cada cliente na plataforma ecommerce da Melhores Compras.' 
;

COMMENT ON COLUMN T_SGV_CLIENTE.ds_senha IS 'Essa coluna irá armazenar a senha de cada cliente na plataforma ecommerce da Melhores Compras.' 
;

COMMENT ON COLUMN T_SGV_CLIENTE.tp_cliente IS 'Essa coluna irá armazenar o tipo de cliente (''PF'', ''PJ'')' 
;

ALTER TABLE T_SGV_CLIENTE 
    ADD CONSTRAINT CK_SGV_CLIENTE_STATUS 
    CHECK (st_cliente IN ('A', 'I')
)
;


ALTER TABLE T_SGV_CLIENTE 
    ADD CONSTRAINT CK_SGV_CLIENTE_ESTRELAS 
    CHECK (qt_estrelas BETWEEN 1 AND 5)
;


ALTER TABLE T_SGV_CLIENTE 
    ADD CONSTRAINT CK_SGV_CLIENTE_TIPO 
    CHECK (tp_cliente IN ('PF', 'PJ'))
;
ALTER TABLE T_SGV_CLIENTE 
    ADD CONSTRAINT PK_SGV_CLIENTE PRIMARY KEY ( nr_cliente ) ;

ALTER TABLE T_SGV_CLIENTE 
    ADD CONSTRAINT UN_SGV_CLIENTE_NOME UNIQUE ( nm_cliente ) ;

CREATE TABLE T_SGV_DEPTO 
    ( 
     cd_depto NUMBER (3)  GENERATED BY DEFAULT AS IDENTITY , 
     nm_depto VARCHAR2 (100)  NOT NULL , 
     st_depto CHAR (1)  NOT NULL 
    ) 
;

COMMENT ON TABLE T_SGV_DEPTO IS 'Armazena os dados dos departamentos da empresa, incluindo o nome do departamento e seu status (ativo ou inativo).'
;

COMMENT ON COLUMN T_SGV_DEPTO.cd_depto IS 'Chave primária que identifica unicamente cada departamento.' 
;

COMMENT ON COLUMN T_SGV_DEPTO.nm_depto IS 'Nome do departamento.' 
;

COMMENT ON COLUMN T_SGV_DEPTO.st_depto IS 'Status do departamento (ex: A = Ativo, I = Inativo).' 
;

ALTER TABLE T_SGV_DEPTO 
    ADD CONSTRAINT CK_SGV_DEPTO_STATUS 
    CHECK (st_depto IN ('A', 'I'))
;
ALTER TABLE T_SGV_DEPTO 
    ADD CONSTRAINT PK_SGV_DEPTO PRIMARY KEY ( cd_depto ) ;

CREATE TABLE T_SGV_END_CLI 
    ( 
     nr_cliente         NUMBER (10)  NOT NULL , 
     cd_logradouro      NUMBER (10)  NOT NULL , 
     nr_end             NUMBER (8)  NOT NULL , 
     ds_complemento_end VARCHAR2 (80) , 
     dt_inicio          DATE  NOT NULL , 
     dt_termino         DATE , 
     st_end             CHAR (1)  NOT NULL 
    ) 
;

COMMENT ON TABLE T_SGV_END_CLI IS 'Armazena os endereços dos clientes, incluindo logradouro, número, complemento, datas de início e término, e status.'
;

COMMENT ON COLUMN T_SGV_END_CLI.nr_cliente IS 'Chave primária e estrangeira que identifica o cliente (relacionada com T_SGV_CLIENTE).' 
;

COMMENT ON COLUMN T_SGV_END_CLI.cd_logradouro IS 'Chave primária e estrangeira que identifica o logradouro (relacionada com T_SGV_LOGRADOURO).' 
;

COMMENT ON COLUMN T_SGV_END_CLI.nr_end IS 'Número do Endereço do Cliente. O número da Rua/Localidade onde o cliente está associado.' 
;

COMMENT ON COLUMN T_SGV_END_CLI.ds_complemento_end IS 'Esta coluna irá receber o complemento do endereço do cliente e seu conteúdo pode ser opcional.' 
;

COMMENT ON COLUMN T_SGV_END_CLI.dt_inicio IS 'Data de início do endereço associado ao cliente.' 
;

COMMENT ON COLUMN T_SGV_END_CLI.dt_termino IS 'Data de término do endereço associado ao cliente.' 
;

COMMENT ON COLUMN T_SGV_END_CLI.st_end IS 'Status do endereço. (A)itvo ou (I)nativo.' 
;

ALTER TABLE T_SGV_END_CLI 
    ADD CONSTRAINT CK_SGV_END_CLI_STATUS 
    CHECK (st_end IN ('A', 'I'))
;


ALTER TABLE T_SGV_END_CLI 
    ADD CONSTRAINT CK_SGV_END_CLI_DATA 
    CHECK (dt_termino IS NULL OR dt_termino > dt_inicio)
;
ALTER TABLE T_SGV_END_CLI 
    ADD CONSTRAINT PK_SGV_END_CLI PRIMARY KEY ( nr_cliente, cd_logradouro ) ;

CREATE TABLE T_SGV_END_FUNC 
    ( 
     cd_funcionario     NUMBER (10)  NOT NULL , 
     cd_logradouro      NUMBER (10)  NOT NULL , 
     nr_end             NUMBER (8)  NOT NULL , 
     ds_complemento_end VARCHAR2 (80) , 
     dt_inicio          DATE  NOT NULL , 
     dt_termino         DATE , 
     st_end             CHAR (1)  NOT NULL 
    ) 
;

COMMENT ON TABLE T_SGV_END_FUNC IS 'Armazena os endereços dos funcionários, incluindo logradouro, número, complemento, datas de início e término, e status.'
;

COMMENT ON COLUMN T_SGV_END_FUNC.cd_funcionario IS 'Chave primária e estrangeira que identifica o funcionário (relacionada com T_SGV_FUNCIONARIO).' 
;

COMMENT ON COLUMN T_SGV_END_FUNC.cd_logradouro IS 'Chave primária e estrangeira que identifica o logradouro (relacionada com T_SGV_LOGRADOURO).' 
;

COMMENT ON COLUMN T_SGV_END_FUNC.nr_end IS 'Número do Endereço do Funcionário. O número da Rua/Localidade onde o funcionário está associado.' 
;

COMMENT ON COLUMN T_SGV_END_FUNC.ds_complemento_end IS 'Complemento do endereço (ex: "Apto 101").' 
;

COMMENT ON COLUMN T_SGV_END_FUNC.dt_inicio IS 'Data de início da vigência do endereço.' 
;

COMMENT ON COLUMN T_SGV_END_FUNC.dt_termino IS 'Data de término da vigência do endereço.' 
;

COMMENT ON COLUMN T_SGV_END_FUNC.st_end IS 'Status do endereço (ex: A = Ativo, I = Inativo).' 
;

ALTER TABLE T_SGV_END_FUNC 
    ADD CONSTRAINT CK_SGV_END_FUNC_STATUS 
    CHECK (st_end IN ('A', 'I'))
;


ALTER TABLE T_SGV_END_FUNC 
    ADD CONSTRAINT Ck_SGV_END_FUNC_DATA 
    CHECK (dt_termino IS NULL OR dt_termino > dt_inicio)
;
ALTER TABLE T_SGV_END_FUNC 
    ADD CONSTRAINT PK_SGV_END_FUNC PRIMARY KEY ( cd_funcionario, cd_logradouro ) ;

CREATE TABLE T_SGV_ESTADO 
    ( 
     sg_estado CHAR (2)  NOT NULL , 
     nm_estado VARCHAR2 (30)  NOT NULL 
    ) 
;

COMMENT ON TABLE T_SGV_ESTADO IS 'Armazena os dados dos estados, incluindo a sigla (ex: SP, RJ) e o nome completo do estado.'
;

COMMENT ON COLUMN T_SGV_ESTADO.sg_estado IS 'Chave primária que identifica unicamente cada estado (sigla de 2 caracteres).' 
;

COMMENT ON COLUMN T_SGV_ESTADO.nm_estado IS 'Nome do estado.' 
;

ALTER TABLE T_SGV_ESTADO 
    ADD CONSTRAINT PK_SGV_ESTADO PRIMARY KEY ( sg_estado ) ;

CREATE TABLE T_SGV_FUNC_TEL 
    ( 
     cd_funcionario NUMBER (10)  NOT NULL , 
     cd_telefone    NUMBER (10)  NOT NULL 
    ) 
;

COMMENT ON TABLE T_SGV_FUNC_TEL IS 'Armazena a relação entre funcionários e seus telefones, permitindo que um funcionário tenha múltiplos telefones cadastrados.'
;

COMMENT ON COLUMN T_SGV_FUNC_TEL.cd_funcionario IS 'Chave primária e estrangeira que identifica o funcionário (relacionada com T_SCV_FUNCIONARIO).' 
;

COMMENT ON COLUMN T_SGV_FUNC_TEL.cd_telefone IS 'Chave primária e estrangeira que identifica o telefone (relacionada com T_SGV_TELEFONE).' 
;

ALTER TABLE T_SGV_FUNC_TEL 
    ADD CONSTRAINT PK_SGV_FUNC_TEL PRIMARY KEY ( cd_funcionario, cd_telefone ) ;

CREATE TABLE T_SGV_FUNCIONARIO 
    ( 
     cd_funcionario    NUMBER (10)  GENERATED ALWAYS AS IDENTITY , 
     cd_depto          NUMBER (3)  NOT NULL , 
     cd_gerente        NUMBER (10) , 
     num_cpf           CHAR (11)  NOT NULL , 
     nm_funcionario    VARCHAR2 (160)  NOT NULL , 
     dt_nascimento     DATE  NOT NULL , 
     sg_sexo_biologico CHAR (1)  NOT NULL , 
     ds_genero         VARCHAR2 (50) , 
     ds_cargo          VARCHAR2 (80)  NOT NULL , 
     vl_salario        NUMBER (10,2) , 
     ds_email          VARCHAR2 (80)  NOT NULL , 
     st_func           CHAR (1)  NOT NULL , 
     dt_cadastramento  DATE  NOT NULL , 
     dt_desligamento   DATE 
    ) 
;

COMMENT ON TABLE T_SGV_FUNCIONARIO IS 'Armazena os dados dos funcionários da empresa.'
;

COMMENT ON COLUMN T_SGV_FUNCIONARIO.cd_funcionario IS 'Chave primária que identifica unicamente cada funcionário.' 
;

COMMENT ON COLUMN T_SGV_FUNCIONARIO.cd_depto IS 'Código do departamento ao qual o funcionário pertence.' 
;

COMMENT ON COLUMN T_SGV_FUNCIONARIO.cd_gerente IS 'Código do gerente do funcionário (auto-relacionamento).' 
;

COMMENT ON COLUMN T_SGV_FUNCIONARIO.num_cpf IS 'CPF do funcionário (11 dígitos numéricos).' 
;

COMMENT ON COLUMN T_SGV_FUNCIONARIO.nm_funcionario IS 'Nome completo do funcionário.' 
;

COMMENT ON COLUMN T_SGV_FUNCIONARIO.dt_nascimento IS 'Data de nascimento do funcionário.' 
;

COMMENT ON COLUMN T_SGV_FUNCIONARIO.sg_sexo_biologico IS 'Sexo biológico do funcionário (M = Masculino, F = Feminino, O=Outro).' 
;

COMMENT ON COLUMN T_SGV_FUNCIONARIO.ds_genero IS 'Gênero com o qual o funcionário se identifica.' 
;

COMMENT ON COLUMN T_SGV_FUNCIONARIO.ds_cargo IS 'Cargo ocupado pelo funcionário na empresa.' 
;

COMMENT ON COLUMN T_SGV_FUNCIONARIO.vl_salario IS 'Salário do funcionário.' 
;

COMMENT ON COLUMN T_SGV_FUNCIONARIO.ds_email IS 'Endereço de e-mail do funcionário.' 
;

COMMENT ON COLUMN T_SGV_FUNCIONARIO.st_func IS 'Status do funcionário (A = Ativo, I = Inativo).' 
;

COMMENT ON COLUMN T_SGV_FUNCIONARIO.dt_cadastramento IS 'Data de cadastramento do funcionário no sistema.' 
;

COMMENT ON COLUMN T_SGV_FUNCIONARIO.dt_desligamento IS 'Data de desligamento do funcionário (se aplicável).' 
;

ALTER TABLE T_SGV_FUNCIONARIO 
    ADD CONSTRAINT CK_SGV_FUNC_STATUS 
    CHECK (st_func IN ('A', 'I'))
;


ALTER TABLE T_SGV_FUNCIONARIO 
    ADD CONSTRAINT CK_SGV_FUNC_SEXO 
    CHECK (sg_sexo_biologico IN ('M', 'F', 'O'))
;


ALTER TABLE T_SGV_FUNCIONARIO 
    ADD CONSTRAINT CK_SGV_FUNC_DATA 
    CHECK (dt_desligamento IS NULL OR dt_desligamento > dt_cadastramento)
;
ALTER TABLE T_SGV_FUNCIONARIO 
    ADD CONSTRAINT PK_SGV_FUNCIONARIO PRIMARY KEY ( cd_funcionario ) ;

ALTER TABLE T_SGV_FUNCIONARIO 
    ADD CONSTRAINT UN_SGV_FUNC_CPF UNIQUE ( num_cpf ) ;

CREATE TABLE T_SGV_LOGRADOURO 
    ( 
     cd_logradouro NUMBER (10)  GENERATED BY DEFAULT AS IDENTITY , 
     cd_bairro     NUMBER (8)  NOT NULL , 
     nm_logradouro VARCHAR2 (160)  NOT NULL , 
     nr_cep        NUMBER (8)  NOT NULL 
    ) 
;

COMMENT ON TABLE T_SGV_LOGRADOURO IS 'Armazena os dados dos logradouros (ruas, avenidas, etc.), incluindo o nome do logradouro, o bairro ao qual pertence e o CEP.'
;

COMMENT ON COLUMN T_SGV_LOGRADOURO.cd_logradouro IS 'Chave primária que identifica unicamente cada logradouro.' 
;

COMMENT ON COLUMN T_SGV_LOGRADOURO.cd_bairro IS 'Chave estrangeira que identifica o bairro ao qual o logradouro pertence.' 
;

COMMENT ON COLUMN T_SGV_LOGRADOURO.nm_logradouro IS 'Nome do logradouro (ex: Rua, Avenida).' 
;

COMMENT ON COLUMN T_SGV_LOGRADOURO.nr_cep IS 'Código de Endereçamento Postal (CEP) do logradouro.' 
;

ALTER TABLE T_SGV_LOGRADOURO 
    ADD CONSTRAINT PK_SGV_LOGRADOURO PRIMARY KEY ( cd_logradouro ) ;

CREATE TABLE T_SGV_PRODUTO 
    ( 
     cd_produto        NUMBER (10)  GENERATED ALWAYS AS IDENTITY , 
     cd_categoria      NUMBER (7)  NOT NULL , 
     ds_produto        VARCHAR2 (80)  NOT NULL , 
     nr_cd_barras_prod VARCHAR2 (50) , 
     vl_unitario       NUMBER (8,2)  NOT NULL , 
     tp_embalagem      VARCHAR2 (15) , 
     st_produto        CHAR (1)  NOT NULL , 
     vl_perc_lucro     NUMBER (8,2) , 
     ds_completa_prod  VARCHAR2 (4000)  NOT NULL 
    ) 
;

COMMENT ON TABLE T_SGV_PRODUTO IS 'Armazena os dados dos produtos disponíveis na empresa, incluindo informações como código de barras, valor unitário, tipo de embalagem, status e descrição completa.'
;

COMMENT ON COLUMN T_SGV_PRODUTO.cd_produto IS 'Chave primária que identifica unicamente cada produto.' 
;

COMMENT ON COLUMN T_SGV_PRODUTO.cd_categoria IS 'Código da categoria à qual o produto pertence.' 
;

COMMENT ON COLUMN T_SGV_PRODUTO.ds_produto IS 'Descrição do produto.' 
;

COMMENT ON COLUMN T_SGV_PRODUTO.nr_cd_barras_prod IS 'Código de barras do produto.' 
;

COMMENT ON COLUMN T_SGV_PRODUTO.vl_unitario IS 'Valor unitário do produto.' 
;

COMMENT ON COLUMN T_SGV_PRODUTO.tp_embalagem IS 'Tipo de embalagem do produto.' 
;

COMMENT ON COLUMN T_SGV_PRODUTO.st_produto IS 'Status do produto (A = Ativo, I = Inativo).' 
;

COMMENT ON COLUMN T_SGV_PRODUTO.vl_perc_lucro IS 'Percentual de lucro sobre o produto.' 
;

COMMENT ON COLUMN T_SGV_PRODUTO.ds_completa_prod IS 'Descrição completa do produto.' 
;

ALTER TABLE T_SGV_PRODUTO 
    ADD CONSTRAINT CK_SGV_PROD_STATUS 
    CHECK (st_produto IN ('A', 'I'))
;
ALTER TABLE T_SGV_PRODUTO 
    ADD CONSTRAINT PK_SGV_PRODUTO PRIMARY KEY ( cd_produto ) ;

ALTER TABLE T_SGV_PRODUTO 
    ADD CONSTRAINT UN_SGV_PRODUTO_DS_PRODUTO UNIQUE ( ds_produto ) ;

CREATE TABLE T_SGV_SAC 
    ( 
     nr_sac                   NUMBER  GENERATED ALWAYS AS IDENTITY , 
     nr_cliente               NUMBER (10)  NOT NULL , 
     cd_produto               NUMBER (10)  NOT NULL , 
     cd_funcionario           NUMBER (10)  NOT NULL , 
     ds_detalhada_sac         VARCHAR2 (4000)  NOT NULL , 
     dt_abertura_sac          DATE  NOT NULL , 
     hr_abertura_sac          NUMBER (2)  NOT NULL , 
     dt_atendimento           DATE , 
     hr_atendimento           NUMBER (2) , 
     nr_tempo_total_sac       NUMBER (10)  NOT NULL , 
     ds_detalhada_retorno_sac CLOB , 
     tp_sac                   CHAR (1)  NOT NULL , 
     st_sac                   CHAR (1)  NOT NULL , 
     nr_indice_satisfacao     NUMBER (3) 
    ) 
;

COMMENT ON TABLE T_SGV_SAC IS 'Armazena os registros de atendimento ao cliente (SAC), incluindo detalhes sobre o cliente, produto, funcionário responsável, datas, horários e status do atendimento.'
;

COMMENT ON COLUMN T_SGV_SAC.nr_sac IS 'Chave primária que identifica unicamente cada registro de SAC.' 
;

COMMENT ON COLUMN T_SGV_SAC.nr_cliente IS 'Código do cliente associado ao SAC.' 
;

COMMENT ON COLUMN T_SGV_SAC.cd_produto IS 'Código do produto relacionado ao SAC.' 
;

COMMENT ON COLUMN T_SGV_SAC.cd_funcionario IS 'Código do funcionário responsável pelo atendimento.' 
;

COMMENT ON COLUMN T_SGV_SAC.ds_detalhada_sac IS 'Descrição detalhada do problema ou solicitação do SAC.' 
;

COMMENT ON COLUMN T_SGV_SAC.dt_abertura_sac IS 'Data de abertura do registro de SAC.' 
;

COMMENT ON COLUMN T_SGV_SAC.hr_abertura_sac IS 'Hora de abertura do registro de SAC.' 
;

COMMENT ON COLUMN T_SGV_SAC.dt_atendimento IS 'Data em que o atendimento foi realizado.' 
;

COMMENT ON COLUMN T_SGV_SAC.hr_atendimento IS 'Hora em que o atendimento foi realizado.' 
;

COMMENT ON COLUMN T_SGV_SAC.nr_tempo_total_sac IS 'Tempo total gasto no atendimento (em horas).' 
;

COMMENT ON COLUMN T_SGV_SAC.ds_detalhada_retorno_sac IS 'Descrição detalhada do retorno ou solução do SAC.' 
;

COMMENT ON COLUMN T_SGV_SAC.tp_sac IS 'Tipo de SAC ( S = Sugestão, C = Reclamação).' 
;

COMMENT ON COLUMN T_SGV_SAC.st_sac IS 'Status do SAC (A = Aberto, F = Finalizado com Sucesso, X= Finalizado com Insatisfação do Cliente, E= Em Atendimento, C = Cancelado).' 
;

COMMENT ON COLUMN T_SGV_SAC.nr_indice_satisfacao IS 'Índice de satisfação do cliente (1  a 100).' 
;

ALTER TABLE T_SGV_SAC 
    ADD CONSTRAINT CK_SGV_SAC_STATUS 
    CHECK (st_sac IN ('A', 'E', 'C', 'F', 'X')
)
;


ALTER TABLE T_SGV_SAC 
    ADD CONSTRAINT CK_SGV_SAC_TIPO 
    CHECK (tp_sac IN ('S', 'C')
)
;
ALTER TABLE T_SGV_SAC 
    ADD CONSTRAINT PK_SGV_SAC PRIMARY KEY ( nr_sac ) ;

CREATE TABLE T_SGV_TELEFONE 
    ( 
     cd_telefone      NUMBER (10)  GENERATED BY DEFAULT AS IDENTITY , 
     cd_tipo_telefone NUMBER (2)  NOT NULL , 
     nr_telefone      VARCHAR2 (9)  NOT NULL , 
     nr_ddd           VARCHAR2 (2)  NOT NULL , 
     nr_ddi           VARCHAR2 (3) 
    ) 
;

COMMENT ON TABLE T_SGV_TELEFONE IS 'Armazena os telefones cadastrados no sistema'
;

COMMENT ON COLUMN T_SGV_TELEFONE.cd_telefone IS 'Chave primária da tabela de telefones' 
;

COMMENT ON COLUMN T_SGV_TELEFONE.cd_tipo_telefone IS 'Chave estrangeira para o tipo de telefone (ex: 1=Celular)' 
;

COMMENT ON COLUMN T_SGV_TELEFONE.nr_telefone IS 'Número do telefone (sem formatação)' 
;

COMMENT ON COLUMN T_SGV_TELEFONE.nr_ddd IS 'DDD do telefone (2 dígitos)' 
;

COMMENT ON COLUMN T_SGV_TELEFONE.nr_ddi IS 'Código do país (DDI) do telefone, composto por 1 a 3 dígitos numéricos (ex: 55=Brasil, 1=EUA).' 
;

ALTER TABLE T_SGV_TELEFONE 
    ADD CONSTRAINT CK_SGV_TELEFONE_DDD 
    CHECK (REGEXP_LIKE(nr_ddd, '^[1-9][0-9]$'))
;


ALTER TABLE T_SGV_TELEFONE 
    ADD CONSTRAINT CK_SGV_TELEFONE_DDI 
    CHECK (REGEXP_LIKE(nr_ddi, '^[0-9]{1,3}$'))
;
ALTER TABLE T_SGV_TELEFONE 
    ADD CONSTRAINT PK_SGV_TELEFONE PRIMARY KEY ( cd_telefone ) ;

CREATE TABLE T_SGV_TIPO_TELEFONE 
    ( 
     cd_tipo_telefone NUMBER (2)  GENERATED BY DEFAULT AS IDENTITY , 
     ds_tipo_telefone VARCHAR2 (50)  NOT NULL 
    ) 
;

COMMENT ON TABLE T_SGV_TIPO_TELEFONE IS 'Tipos de telefones cadastráveis no sistema'
;

COMMENT ON COLUMN T_SGV_TIPO_TELEFONE.cd_tipo_telefone IS 'Código sequencial do tipo' 
;

COMMENT ON COLUMN T_SGV_TIPO_TELEFONE.ds_tipo_telefone IS 'Descrição do tipo de telefone
' 
;

ALTER TABLE T_SGV_TIPO_TELEFONE 
    ADD CONSTRAINT PK_SGV_TIPO_TELEFONE PRIMARY KEY ( cd_tipo_telefone ) ;

CREATE TABLE T_SGV_VIDEO 
    ( 
     cd_video         NUMBER (10)  GENERATED ALWAYS AS IDENTITY , 
     cd_produto       NUMBER (10)  NOT NULL , 
     cd_classificacao NUMBER (7)  NOT NULL , 
     st_video         CHAR (1)  NOT NULL 
    ) 
;

COMMENT ON TABLE T_SGV_VIDEO IS 'Armazena os dados dos vídeos, incluindo o produto relacionado, a classificação e o status.'
;

COMMENT ON COLUMN T_SGV_VIDEO.cd_video IS 'Chave primária que identifica unicamente cada vídeo.' 
;

COMMENT ON COLUMN T_SGV_VIDEO.cd_produto IS 'Chave estrangeira que identifica o produto relacionado ao vídeo.' 
;

COMMENT ON COLUMN T_SGV_VIDEO.cd_classificacao IS 'Chave estrangeira que identifica a classificação do vídeo.' 
;

COMMENT ON COLUMN T_SGV_VIDEO.st_video IS 'Status do vídeo (ex: A = Ativo, I = Inativo).' 
;

ALTER TABLE T_SGV_VIDEO 
    ADD CONSTRAINT CK_SGV_VIDEO_STATUS 
    CHECK (st_video IN ('A', 'I')
)
;
ALTER TABLE T_SGV_VIDEO 
    ADD CONSTRAINT PK_SGV_VIDEO PRIMARY KEY ( cd_video ) ;

CREATE TABLE T_SGV_VISUALIZACAO_VIDEO 
    ( 
     cd_vizualizacao NUMBER (10)  GENERATED ALWAYS AS IDENTITY , 
     cd_video        NUMBER (10)  NOT NULL , 
     nr_cliente      NUMBER (10)  NOT NULL , 
     dt_vizualizacao TIMESTAMP  NOT NULL 
    ) 
;

COMMENT ON TABLE T_SGV_VISUALIZACAO_VIDEO IS 'Armazena os registros de visualização de vídeos pelos clientes, incluindo o código do vídeo, o cliente que visualizou e a data/hora da visualização.'
;

COMMENT ON COLUMN T_SGV_VISUALIZACAO_VIDEO.cd_vizualizacao IS 'Chave primária que identifica unicamente cada visualização de vídeo.' 
;

COMMENT ON COLUMN T_SGV_VISUALIZACAO_VIDEO.cd_video IS 'Chave estrangeira que referencia o vídeo assistido.' 
;

COMMENT ON COLUMN T_SGV_VISUALIZACAO_VIDEO.nr_cliente IS 'Chave estrangeira que referencia o cliente que assistiu ao vídeo.' 
;

COMMENT ON COLUMN T_SGV_VISUALIZACAO_VIDEO.dt_vizualizacao IS 'Data e hora exatas em que o vídeo foi assistido pelo cliente.' 
;

ALTER TABLE T_SGV_VISUALIZACAO_VIDEO 
    ADD CONSTRAINT PK_T_SGV_VISUALIZACAO_VIDEO PRIMARY KEY ( cd_vizualizacao ) ;

ALTER TABLE T_SGV_BAIRRO 
    ADD CONSTRAINT FK_SGV_BAIRRO_CIDADE FOREIGN KEY 
    ( 
     cd_cidade
    ) 
    REFERENCES T_SGV_CIDADE 
    ( 
     cd_cidade
    ) 
;

ALTER TABLE T_SGV_CIDADE 
    ADD CONSTRAINT FK_SGV_CIDADE_ESTADO FOREIGN KEY 
    ( 
     sg_estado
    ) 
    REFERENCES T_SGV_ESTADO 
    ( 
     sg_estado
    ) 
;

ALTER TABLE T_SGV_CLI_FISICA 
    ADD CONSTRAINT FK_SGV_CLI_FISICA_CLIENTE FOREIGN KEY 
    ( 
     nr_cliente
    ) 
    REFERENCES T_SGV_CLIENTE 
    ( 
     nr_cliente
    ) 
;

ALTER TABLE T_SGV_CLI_JURIDICA 
    ADD CONSTRAINT FK_SGV_CLI_JURIDICA_CLIENTE FOREIGN KEY 
    ( 
     nr_cliente
    ) 
    REFERENCES T_SGV_CLIENTE 
    ( 
     nr_cliente
    ) 
;

ALTER TABLE T_SGV_CLI_TEL 
    ADD CONSTRAINT FK_SGV_CLI_TEL_CLIENTE FOREIGN KEY 
    ( 
     nr_cliente
    ) 
    REFERENCES T_SGV_CLIENTE 
    ( 
     nr_cliente
    ) 
;

ALTER TABLE T_SGV_CLI_TEL 
    ADD CONSTRAINT FK_SGV_CLI_TEL_TELEFONE FOREIGN KEY 
    ( 
     cd_telefone
    ) 
    REFERENCES T_SGV_TELEFONE 
    ( 
     cd_telefone
    ) 
;

ALTER TABLE T_SGV_END_CLI 
    ADD CONSTRAINT FK_SGV_END_CLI_CLIENTE FOREIGN KEY 
    ( 
     nr_cliente
    ) 
    REFERENCES T_SGV_CLIENTE 
    ( 
     nr_cliente
    ) 
;

ALTER TABLE T_SGV_END_CLI 
    ADD CONSTRAINT FK_SGV_END_CLI_LOGRADOURO FOREIGN KEY 
    ( 
     cd_logradouro
    ) 
    REFERENCES T_SGV_LOGRADOURO 
    ( 
     cd_logradouro
    ) 
;

ALTER TABLE T_SGV_END_FUNC 
    ADD CONSTRAINT FK_SGV_END_FUNC_FUNC FOREIGN KEY 
    ( 
     cd_funcionario
    ) 
    REFERENCES T_SGV_FUNCIONARIO 
    ( 
     cd_funcionario
    ) 
;

ALTER TABLE T_SGV_END_FUNC 
    ADD CONSTRAINT FK_SGV_END_FUNC_LOGRADOURO FOREIGN KEY 
    ( 
     cd_logradouro
    ) 
    REFERENCES T_SGV_LOGRADOURO 
    ( 
     cd_logradouro
    ) 
;

ALTER TABLE T_SGV_FUNCIONARIO 
    ADD CONSTRAINT FK_SGV_FUNC_DEPTO FOREIGN KEY 
    ( 
     cd_depto
    ) 
    REFERENCES T_SGV_DEPTO 
    ( 
     cd_depto
    ) 
;

ALTER TABLE T_SGV_FUNCIONARIO 
    ADD CONSTRAINT FK_SGV_FUNC_FUNC FOREIGN KEY 
    ( 
     cd_gerente
    ) 
    REFERENCES T_SGV_FUNCIONARIO 
    ( 
     cd_funcionario
    ) 
;

ALTER TABLE T_SGV_FUNC_TEL 
    ADD CONSTRAINT FK_SGV_FUNC_TEL_FUNC FOREIGN KEY 
    ( 
     cd_funcionario
    ) 
    REFERENCES T_SGV_FUNCIONARIO 
    ( 
     cd_funcionario
    ) 
;

ALTER TABLE T_SGV_FUNC_TEL 
    ADD CONSTRAINT FK_SGV_FUNC_TEL_TELEFONE FOREIGN KEY 
    ( 
     cd_telefone
    ) 
    REFERENCES T_SGV_TELEFONE 
    ( 
     cd_telefone
    ) 
;

ALTER TABLE T_SGV_LOGRADOURO 
    ADD CONSTRAINT FK_SGV_LOGRADOURO_BAIRRO FOREIGN KEY 
    ( 
     cd_bairro
    ) 
    REFERENCES T_SGV_BAIRRO 
    ( 
     cd_bairro
    ) 
;

ALTER TABLE T_SGV_PRODUTO 
    ADD CONSTRAINT FK_SGV_PROD_CATEG_PROD FOREIGN KEY 
    ( 
     cd_categoria
    ) 
    REFERENCES T_SGV_CATEGORIA_PROD 
    ( 
     cd_categoria
    ) 
;

ALTER TABLE T_SGV_SAC 
    ADD CONSTRAINT FK_SGV_SAC_CLIENTE FOREIGN KEY 
    ( 
     nr_cliente
    ) 
    REFERENCES T_SGV_CLIENTE 
    ( 
     nr_cliente
    ) 
;

ALTER TABLE T_SGV_SAC 
    ADD CONSTRAINT FK_SGV_SAC_FUNC FOREIGN KEY 
    ( 
     cd_funcionario
    ) 
    REFERENCES T_SGV_FUNCIONARIO 
    ( 
     cd_funcionario
    ) 
;

ALTER TABLE T_SGV_SAC 
    ADD CONSTRAINT FK_SGV_SAC_PROD FOREIGN KEY 
    ( 
     cd_produto
    ) 
    REFERENCES T_SGV_PRODUTO 
    ( 
     cd_produto
    ) 
;

ALTER TABLE T_SGV_TELEFONE 
    ADD CONSTRAINT FK_SGV_TELEFONE_TIPO_TELEFONE FOREIGN KEY 
    ( 
     cd_tipo_telefone
    ) 
    REFERENCES T_SGV_TIPO_TELEFONE 
    ( 
     cd_tipo_telefone
    ) 
;

ALTER TABLE T_SGV_VIDEO 
    ADD CONSTRAINT FK_SGV_VIDEO_CLASSIF_VIDEO FOREIGN KEY 
    ( 
     cd_classificacao
    ) 
    REFERENCES T_SGV_CLASSIFICACAO_VIDEO 
    ( 
     cd_classificacao
    ) 
;

ALTER TABLE T_SGV_VIDEO 
    ADD CONSTRAINT FK_SGV_VIDEO_PROD FOREIGN KEY 
    ( 
     cd_produto
    ) 
    REFERENCES T_SGV_PRODUTO 
    ( 
     cd_produto
    ) 
;

ALTER TABLE T_SGV_VISUALIZACAO_VIDEO 
    ADD CONSTRAINT FK_SGV_VISU_VIDEO_CLIENTE FOREIGN KEY 
    ( 
     nr_cliente
    ) 
    REFERENCES T_SGV_CLIENTE 
    ( 
     nr_cliente
    ) 
;

ALTER TABLE T_SGV_VISUALIZACAO_VIDEO 
    ADD CONSTRAINT FK_SGV_VISU_VIDEO_VIDEO FOREIGN KEY 
    ( 
     cd_video
    ) 
    REFERENCES T_SGV_VIDEO 
    ( 
     cd_video
    ) 
;

CREATE OR REPLACE TRIGGER ARC_FK_ARCO_C_T_SGV_CLI_FISICA 
BEFORE INSERT OR UPDATE OF nr_cliente 
ON T_SGV_CLI_FISICA 
FOR EACH ROW 
DECLARE 
    d CHAR (2); 
BEGIN 
    SELECT A.tp_cliente INTO d 
    FROM T_SGV_CLIENTE A 
    WHERE A.nr_cliente = :new.nr_cliente; 
    IF (d IS NULL OR d <> 'PF') THEN 
        raise_application_error(-20223,'FK FK_SGV_CLI_FISICA_CLIENTE in Table T_SGV_CLI_FISICA violates Arc constraint on Table T_SGV_CLIENTE - discriminator column tp_cliente doesn''t have value ''PF'''); 
    END IF; 
    EXCEPTION 
    WHEN NO_DATA_FOUND THEN 
        NULL; 
    WHEN OTHERS THEN 
        RAISE; 
END; 
/

CREATE OR REPLACE TRIGGER ARC_FK_ARCO_T_SGV_CLI_JURIDICA 
BEFORE INSERT OR UPDATE OF nr_cliente 
ON T_SGV_CLI_JURIDICA 
FOR EACH ROW 
DECLARE 
    d CHAR (2); 
BEGIN 
    SELECT A.tp_cliente INTO d 
    FROM T_SGV_CLIENTE A 
    WHERE A.nr_cliente = :new.nr_cliente; 
    IF (d IS NULL OR d <> 'PJ') THEN 
        raise_application_error(-20223,'FK FK_SGV_CLI_JURIDICA_CLIENTE in Table T_SGV_CLI_JURIDICA violates Arc constraint on Table T_SGV_CLIENTE - discriminator column tp_cliente doesn''t have value ''PJ'''); 
    END IF; 
    EXCEPTION 
    WHEN NO_DATA_FOUND THEN 
        NULL; 
    WHEN OTHERS THEN 
        RAISE; 
END; 
/



-- Relatório do Resumo do Oracle SQL Developer Data Modeler: 
-- 
-- CREATE TABLE                            21
-- CREATE INDEX                             0
-- ALTER TABLE                             70
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           2
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0